language: python
dist: precise
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy" #commenting out pypy as does not work on trusty yet (travis new default)
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: python setup.py test
#add line to force commit
